Repository radical-cybertools/radical.utils, pull requests merged in 2019-02, with the labels that each got.

#142 Config files for PEP8 and pylint. PEP8 corrections
  .flake8
  .pylintrc
  .travis.yml
  setup.py
  src/radical/utils/algorithms.py
  src/radical/utils/benchmark.py
  src/radical/utils/daemonize.py
  src/radical/utils/debug.py
  src/radical/utils/dict_mixin.py
  src/radical/utils/futures.py
  src/radical/utils/get_version.py
  src/radical/utils/ids.py
  src/radical/utils/lease_manager.py
  src/radical/utils/lockable.py
  src/radical/utils/logger.py
  src/radical/utils/misc.py
  src/radical/utils/object_cache.py
Labels: layer:utils, type:enhancement

#151 Feature/zmq port
  examples/zmq/README.md
  examples/zmq/protocols.md
  examples/zmq/pubsub/pub.py
  examples/zmq/pubsub/pubsub.py
  examples/zmq/pubsub/sub.py
  examples/zmq/queue/get.py
  examples/zmq/queue/put.py
  examples/zmq/queue/queue.py
  setup.py
  src/radical/utils/__init__.py
  src/radical/utils/misc.py
  src/radical/utils/ru_regex.py
  src/radical/utils/zmq/__init__.py
  src/radical/utils/zmq/bridge.py
  src/radical/utils/zmq/pubsub.py
  src/radical/utils/zmq/queue.py
  tests/unittests/test_lease_manager.py
  tests/unittests/test_misc.py
  tests/unittests/test_poll.py
  tests/unittests/test_regex.py
Labels: priority:medium, topic:communication, type:feature

#153 Fix/setup tests
  setup.py
  src/radical/utils/__init__.py
  src/radical/utils/atfork/atfork.py
  src/radical/utils/atfork/stdlib_fixer.py
  src/radical/utils/atfork/tests/test_atfork.py
  src/radical/utils/atfork/tests/test_stdlib_fixer.py
  src/radical/utils/benchmark.py
  src/radical/utils/misc.py
  src/radical/utils/shell.py
  src/radical/utils/test_config.py
  src/radical/utils/testing.py
  tests/configs/default.cfg
  tests/run_tests.py
  tests/unittests/test_config.py
  tests/unittests/test_lease_manager.py
  tests/unittests/test_reporter.py
Labels: priority:medium, topic:testing, type:enhancement

#154 Fix/setup
  setup.py
  src/radical/utils/__init__.py
Labels: priority:low, topic:testing, type:enhancement

#152 add expandvars + unitttests + ReString fixes
  .travis.yml
  src/radical/utils/misc.py
  src/radical/utils/ru_regex.py
  tests/unittests/test_misc.py
Labels: priority:high, topic:api, type:feature

#150 Fix/state event duplication
  src/radical/utils/profile.py
Labels: priority:medium, topic:data, type:bug

#130 Feature/json config reader
  setup.py
  src/radical/utils/__init__.py
  src/radical/utils/config.py
  src/radical/utils/config/__init__.py
  src/radical/utils/config/config.py
  src/radical/utils/config/configfile.py
  src/radical/utils/misc.py
  src/radical/utils/plugin_manager.py
  src/radical/utils/queue_network/__init__.py
  src/radical/utils/queue_network/network.py
  src/radical/utils/queue_network/node.py
  src/radical/utils/queue_network/queue.py
  tests/unittests/data/resource_yale.json
  tests/unittests/test_config.py
Labels: layer:rct, layer:rp, layer:saga, layer:utils, priority:high, topic:api, type:enhancement
