Repository radical-cybertools/radical.utils, pull requests merged in 2020-06, with the labels that each got.

#223 Name for cnt-file (inside method generate_id) is defined incorrectly
  src/radical/utils/ids.py
  tests/test_cases/ids.00000.json
  tests/unittests/test_ids.py
Labels: layer:utils, priority:medium, type:bug

#236 silence ZMQ profiles
  src/radical/utils/zmq/bridge.py
  src/radical/utils/zmq/pubsub.py
  src/radical/utils/zmq/queue.py
Labels: priority:high, topic:communication, type:performance

#239 Feature/metric expand
  src/radical/utils/__init__.py
  src/radical/utils/json_io.py
  tests/unittests/test_ids.py
  tests/unittests/test_json.py
Labels: layer:analytics, priority:medium, topic:data, type:feature

#240 remove obsolete code, increase coverage
  src/radical/utils/url.py
  tests/unittests/test_url.py
Labels: priority:low, topic:testing, type:enhancement
