Repository radical-cybertools/radical.utils, pull requests merged in 2020-02, with the labels that each got.

#211 speed up uid generation
  src/radical/utils/ids.py
Labels: priority:medium, type:performance

#207 no timeout, no termination
  src/radical/utils/heartbeat.py
Labels: priority:low, topic:api, topic:termination, type:enhancement

#208 add verbosity option to `radical-stack`
  bin/radical-stack
Labels: priority:low, topic:deployment, type:feature

#209 update README
  README.md
Labels: priority:low, type:documentation

#216 Handling 'None' value in method misc.as_tuple()
  src/radical/utils/misc.py
Labels: priority:medium, type:bug

#218 change bulk defaults
  src/radical/utils/zmq/queue.py
Labels: priority:medium, type:performance

#219 change bulk defaults
  src/radical/utils/zmq/queue.py
Labels: layer:analytics, priority:low, type:refactoring

#220 silence queue logs
  .flake8
  src/radical/utils/zmq/pubsub.py
Labels: layer:rp, priority:high, topic:data, type:performance
