Repository radical-cybertools/radical.utils, pull requests merged in 2020-08, with the labels that each got.

#254 Min python version 3.6
  .travis.yml
  bin/radical-stack-clone
  bin/radical-utils-scheduler.py
  setup.py
  tests/unittests/test_algorithms.py
  tests/unittests/test_description.py
  tests/unittests/test_json.py
  tests/unittests/test_locks.py
  tests/unittests/test_object_cache.py
  tests/unittests/test_url.py
Labels: priority:medium, topic:deployment, type:enhancement

#250 add script to function converter
  src/radical/utils/misc.py
  src/radical/utils/shell.py
  tests/unittests/test_misc.py
Labels: priority:medium, topic:execution, type:feature

#249 line buffering is not multiprocess-safe for high-frequency writes
  src/radical/utils/profile.py
Labels: priority:critical, topic:data, type:bug

#243 Feature/config inheritance
  src/radical/utils/config.py
  src/radical/utils/configs/utils_default.json
  src/radical/utils/description.py
  src/radical/utils/dict_mixin.py
  src/radical/utils/misc.py
  src/radical/utils/munch.py
  src/radical/utils/zmq/queue.py
  tests/unittests/test_algorithms.py
  tests/unittests/test_config.py
  tests/unittests/test_description.py
  tests/unittests/test_json.py
  tests/unittests/test_munch.py
  tests/unittests/test_poll.py
  tests/unittests/test_reporter.py
  tests/unittests/test_zmq_queue.py
Labels: priority:medium, type:refactoring

#256 Fix/epoch
  bin/radical-utils-gtod
  setup.py
Labels: priority:high, topic:deployment, type:enhancement

#257 Remove lib `munch` as a dependency
  setup.py
Labels: priority:medium, topic:deployment

#258 remove code duplication, fix a test
  src/radical/utils/config.py
  tests/unittests/test_description.py
Labels: priority:medium, topic:testing, type:bug

#259 Fix to respect default values of Munch-based attributes
  src/radical/utils/munch.py
  tests/unittests/test_misc.py
  tests/unittests/test_munch.py
Labels: priority:high, topic:api

#260 handle defaults the same way as schema
  src/radical/utils/description.py
  src/radical/utils/munch.py
  tests/unittests/test_description.py
  tests/unittests/test_munch.py
  tests/unittests/test_profiler.py
Labels: priority:medium, topic:api, type:enhancement
