Repository radical-cybertools/radical.utils, pull requests merged in 2021-04, with the labels that each got.

#290 multiple namespaces to load plugins from
  src/radical/utils/debug.py
  src/radical/utils/plugin_manager.py
  tests/unittests/test_plugin_manager.py
Labels: priority:high, topic:api, type:enhancement

#292 Fix/munch defaults
  src/radical/utils/munch.py
Labels: priority:high, topic:api, type:enhancement

#286 zmq server and client classes
  examples/zmq_client.py
  examples/zmq_server.py
  src/radical/utils/__init__.py
  src/radical/utils/debug.py
  src/radical/utils/heartbeat.py
  src/radical/utils/zmq/__init__.py
  src/radical/utils/zmq/bridge.py
  src/radical/utils/zmq/client.py
  src/radical/utils/zmq/pubsub.py
  src/radical/utils/zmq/queue.py
  src/radical/utils/zmq/server.py
  src/radical/utils/zmq/utils.py
Labels: topic:api, topic:communication, type:feature

#294 Feature/bulk pubsub
  examples/zmq_client.py
  examples/zmq_server.py
  src/radical/utils/__init__.py
  src/radical/utils/debug.py
  src/radical/utils/heartbeat.py
  src/radical/utils/json_io.py
  src/radical/utils/zmq/__init__.py
  src/radical/utils/zmq/bridge.py
  src/radical/utils/zmq/client.py
  src/radical/utils/zmq/pubsub.py
  src/radical/utils/zmq/queue.py
  src/radical/utils/zmq/server.py
  src/radical/utils/zmq/utils.py
  tests/unittests/test_zmq_queue.py
Labels: priority:medium, topic:communication, type:enhancement

#293 Feature/env isolation
  .flake8
  bin/radical-utils-env.sh
  bin/ru.json.sh
  src/radical/utils/__init__.py
  src/radical/utils/env.py
  src/radical/utils/json_io.py
  src/radical/utils/shell.py
  src/radical/utils/zmq/queue.py
  tests/unittests/test_env.py
  tests/unittests/test_zmq_queue.py
Labels: priority:high, topic:execution, type:documentation, type:enhancement

#291 make check on set and type cast optional
  src/radical/utils/munch.py
  tests/unittests/test_munch.py
Labels: priority:high, topic:api, type:enhancement

#296 Fix method `get_hostname`
  src/radical/utils/misc.py
Labels: priority:medium, type:enhancement

#297 Changes related to GitHub actions
  .codecov.yml
  .github/workflows/python-app.yml
  README.md
Labels: topic:testing
