Repository radical-cybertools/radical.utils, pull requests merged in 2021-09, with the labels that each got.

#295 Feature/registry
  .pylintrc
  examples/zmq_registry.py
  src/radical/utils/__init__.py
  src/radical/utils/atfork/__init__.py
  src/radical/utils/json_io.py
  src/radical/utils/queue_network/__init__.py
  src/radical/utils/scheduler/__init__.py
  src/radical/utils/zmq/__init__.py
  src/radical/utils/zmq/client.py
  src/radical/utils/zmq/registry.py
  src/radical/utils/zmq/server.py
  tests/unittests/test_host.py
  tests/unittests/test_zmq_client.py
  tests/unittests/test_zmq_registry.py
Labels: priority:medium, topic:api, topic:communication, topic:data, type:feature

#310 Disable `os.setsid` in `ru.daemonize`
  src/radical/utils/daemon.py
Labels: layer:rp, priority:medium, topic:execution

#309 add `debug_1`, `debug_2` etc as additional log levels
  src/radical/utils/logger.py
  tests/unittests/test_logger.py
Labels: priority:medium, topic:api, type:enhancement

#299 Feature/env isolation
  bin/radical-utils-env.sh
  setup.py
  src/radical/utils/__init__.py
  src/radical/utils/env.py
  src/radical/utils/flux.py
  src/radical/utils/host.py
  src/radical/utils/misc.py
  src/radical/utils/zmq/server.py
  tests/unittests/test_env.py
Labels: priority:high, topic:api, topic:execution, type:enhancement

#315 Feature/flux pickup
  .github/workflows/python-app.yml
  src/radical/utils/flux.py
  tests/integration_tests/test_flux.py
Labels: priority:high, type:feature

#313 Update host.py
  src/radical/utils/host.py
  tests/unittests/test_host.py
Labels: priority:medium, type:enhancement

#316 add missing import
  src/radical/utils/__init__.py
Labels: priority:critical, topic:api, type:bug

#317 ensure var initialization
  src/radical/utils/logger.py
Labels: priority:critical, type:bug
