Repository radical-cybertools/radical.utils, pull requests merged in 2022-12, with the labels that each got.

#364 move GH tests to Python 3.7
  .github/workflows/python-app.yml
  bin/radical-stack-clone
Labels: layer:rct, priority:high, topic:testing, type:refactoring

#363 Feature/get debug level
  CHANGES.md
  src/radical/utils/logger.py
Labels: priority:medium, topic:api, type:enhancement

#367 fixed error related to default value None
  src/radical/utils/typeddict.py
  tests/unittests/test_typeddict.py
Labels: layer:rp, priority:high, type:bug

#366 Feature/no rmq
  .pylintrc
  src/radical/utils/zmq/bridge.py
  src/radical/utils/zmq/pubsub.py
  src/radical/utils/zmq/queue.py
  src/radical/utils/zmq/server.py
Labels: priority:high, topic:resource, type:enhancement
