Repository radical-cybertools/radical.utils, pull requests merged in 2022-02, with the labels that each got.

#329 `Pytest` - changed signature for `pytest.exit`
  src/radical/utils/testing.py
Labels: layer:utils, priority:high, topic:testing

#328 Fixed conda deactivate (`env_deactivate`)
  bin/radical-utils-env.sh
Labels: layer:rp, priority:high, type:bug

#326 only unset superfluous env vars on `env_write`
  src/radical/utils/env.py
Labels: layer:rp, priority:critical, topic:resource, type:bug

#327 Remove `Request` and `Response` classes
  examples/zmq_server.py
  src/radical/utils/__init__.py
  src/radical/utils/algorithms.py
  src/radical/utils/debug.py
  src/radical/utils/gtod.c
  src/radical/utils/ids.py
  src/radical/utils/logger.py
  src/radical/utils/misc.py
  src/radical/utils/zmq/__init__.py
  src/radical/utils/zmq/bridge.py
  src/radical/utils/zmq/client.py
  src/radical/utils/zmq/pubsub.py
  src/radical/utils/zmq/queue.py
  src/radical/utils/zmq/server.py
  src/radical/utils/zmq/utils.py
  tests/unittests/test_zmq_client.py
  tests/unittests/test_zmq_server.py
Labels: priority:medium, topic:communication, type:refactoring

#333 add `sh_quote()`
  src/radical/utils/__init__.py
  src/radical/utils/shell.py
  tests/unittests/test_ids.py
  tests/unittests/test_shell.py
Labels: layer:rp, priority:critical, topic:execution, type:enhancement

#325 `TypedDict` as `Munch`-successor
  src/radical/utils/__init__.py
  src/radical/utils/config.py
  src/radical/utils/description.py
  src/radical/utils/dict_mixin.py
  src/radical/utils/misc.py
  src/radical/utils/munch.py
  src/radical/utils/typeddict.py
  tests/unittests/test_config.py
  tests/unittests/test_description.py
  tests/unittests/test_munch.py
  tests/unittests/test_typeddict.py
Labels: priority:medium, type:refactoring

#335 `TypedDict` property `__class__` to masquerade as `dict` for `isinstance` calls
  src/radical/utils/typeddict.py
  tests/unittests/test_typeddict.py
Labels: layer:rp, priority:medium, topic:data, type:enhancement

#338 CI: use RCT devel packages
  .github/workflows/python-app.yml
Labels: priority:medium, topic:testing

#337 Update `TypedDict` base methods to be aligned with `dict` type
  src/radical/utils/typeddict.py
  tests/unittests/test_typeddict.py
Labels: priority:medium, type:enhancement

#339 Fixed exception using `TypeError`
  src/radical/utils/typeddict.py
  tests/unittests/test_typeddict.py
Labels: priority:high, topic:data

#342 CI update
  .github/workflows/python-app.yml
Labels: priority:medium, topic:testing

#341 remove Munch and demunch from exported names
  examples/demunch_timing.py
  src/radical/utils/__init__.py
  src/radical/utils/typeddict.py
Labels: priority:medium, type:refactoring
